In [1]:
# 动手学深度学习-Day1
# 1-d 向量
# 2-d 矩阵
# 3-d RGB图片(宽*高*通道)
# 4-d 一个RGB图片批量(批量大小*宽*高*通道)
# 5-d 一个视频批量(批量大小*时间*宽*高*通道)
# 批量大小=batch_size

In [2]:
import torch
import os
import pandas as pd

In [3]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
# shape属性访问张量的形状
x.shape

torch.Size([12])

In [5]:
# numel属性访问张量中元素的总数
x.numel()

12

In [6]:
# reshape不改变张量元素值和数量，只改变形状
# 例子为三行四列
x = x.reshape(3,4)
print(x)
y = x.reshape(2,6)
print(y)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])


In [7]:
# torch.tensor创建一个固定的张量
torch.tensor([[2,1,4,3],[1,2,3,4],[4,3,2,1]]).shape

torch.Size([3, 4])

In [8]:
# torch.tensor创建一个固定的张量
torch.tensor([[[2,1,4,3],[1,2,3,4],[4,3,2,1]]]).shape

torch.Size([1, 3, 4])

In [9]:
x=torch.tensor([1.0,2,4,8])
y=torch.tensor([2,2,2,2])
x+y,x-y,x*y,x/y,x**y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [10]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [11]:
X = torch.arange(12,dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0,1,4,3],[1,2,3,4],[4,3,2,1]])
torch.cat((X,Y),dim=0),torch.cat((X,Y),dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [12]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [13]:
# 广播机制
a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape((1,2))
a,b
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [14]:
# 这里的基础操作其实很简单，有python基础的一学就会
os.makedirs(os.path.join('..','data'),exist_ok=True)
data_file = os.path.join('..', 'data', 'house_tiny.csv')
with open(data_file,'w') as f:
    f.write('NumRooms,Alley,Price\n')
    f.write('NA,Pave,127500\n')
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

In [15]:
data = pd.read_csv(data_file)
data

NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000

In [16]:
inputs, outputs = data.iloc[:,0:2],data.iloc[:,2]
inputs = inputs.fillna(inputs.mean())
print(inputs)

   NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN


C:\Users\Administrator\AppData\Local\Temp\ipykernel_64592\3751365057.py:2: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  inputs = inputs.fillna(inputs.mean())


In [17]:
inputs = pd.get_dummies(inputs,dummy_na=True)
print(inputs)

   NumRooms  Alley_Pave  Alley_nan
0       3.0           1          0
1       2.0           0          1
2       4.0           0          1
3       3.0           0          1


In [18]:
X,y = torch.tensor(inputs.values),torch.tensor(outputs.values)
X,y

(tensor([[3., 1., 0.],
         [2., 0., 1.],
         [4., 0., 1.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500, 106000, 178100, 140000]))

||标量x（1，）|向量X（n，1）|矩阵X（n，k）|
|:---:|:---:|:---:|:---:|
|**标量x（1，）**|标量（1，）|行向量（1，n）|矩阵（k，n）|
|**向量X（m，1）**|列向量（m，1）|矩阵（m，n）|三维（m，k，n）|
|**矩阵X（m，s）**|矩阵（m，s）|三维（m，s，n）|四维（m，s，k，n）|

In [19]:
# 自动求导 高级货！
# 注意噢只有浮点型张量，才可以计算梯度
# 这里的例子是y=2xTx x是列向量
# 内积求偏导是另一个的转置嘎
x = torch.arange(4.) # 所以这里是4.0
x

tensor([0., 1., 2., 3.])

$x=[x_1,x_2,...x_n]^T$\
$\frac {\partial y}{\partial x}=[\frac {\partial y}{\partial x_1},\frac {\partial y}{\partial x_2},...,\frac {\partial y}{\partial x_n}]$\
$y=2x^Tx$\
$u=x^T,v=x$\
$\frac {\partial y}{\partial x}=u^T \frac {\partial v}{\partial x}+v^T \frac {\partial u}{\partial x}$

In [20]:
x.requires_grad_(True)
x.grad

In [21]:
y = 2*torch.dot(x,x)
y

tensor(28., grad_fn=<MulBackward0>)

In [22]:
# 反向传播
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [23]:
x.grad == 4*x

tensor([True, True, True, True])

In [24]:
# Pytorch累积梯度，zero进行清除
x.grad.zero_()
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [25]:
y = x.sum()
y.backward()
x.grad

tensor([2., 2., 2., 2.])

In [26]:
x.grad.zero_()
y = x * x
y.sum().backward()
x.grad

tensor([0., 2., 4., 6.])